[2022-08-30 03:00:54,191] ERROR [django.request.log_response:241] Internal Server Error: /appointments/12/
[2022-08-30 03:03:48,257] ERROR [django.request.log_response:241] Internal Server Error: /login/
[2022-08-30 03:03:48,717] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-08-30 03:16:12,561] WARNING [django.request.log_response:241] Not Found: /favicon.ico
[2022-08-30 05:26:37,661] ERROR [django.request.log_response:241] Internal Server Error: /appointments/12/
[2022-08-30 05:47:51,156] ERROR [django.request.log_response:241] Internal Server Error: /user/me/appointments/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Appointment is not JSON serializable
